name: valgrind

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: valgrind
      run: sudo apt install valgrind
    - name: valgrind
      run: valgrind --enable=all 3_Implementation

